#!/usr/bin/env zsh

# Logging utilities
e_header()  { echo -e "\n\033[1m$@\033[0m"; }
e_success() { echo -e " \033[1;32m✔\033[0m  $@"; }

main () {
  e_header "Applying dotfiles with stow..."
  for package in zsh neovim git tmux bash; do
    stow -D -t $HOME $package  # Remove old symlinks
    stow -t $HOME $package     # Apply new symlinks
  done

  e_success "Dotfiles setup complete!"
}

main "$@"
